---
abstract: 'Create HTTP requests from templates'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Base: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Request-FromTemplate
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor: '0'
  HTTP::Message: '0'
  HTTP::Request: '0'
  Template: '0'
  perl: '5.006'
resources:
  repository: git://github.com/Corion/http-request-fromtemplate.git
version: '0.05'
